config/routes.rb
Blazquest::Application.routes.draw do
  resources :tartans

  resources :mottos

  resources :shields

  resources :surnames

  get "pages/index"

  root 'pages#index'

end

app/models/motto.rb
class Motto < ActiveRecord::Base
	belongs_to :surname
end

app/models/shield.rb
class Shield < ActiveRecord::Base
	belongs_to :surname
end

app/models/surname.rb
class Surname < ActiveRecord::Base
	has_many :shields
	has_many :mottos
	has_many :tartans
end

app/models/tartan.rb
class Tartan < ActiveRecord::Base
	belongs_to :surname
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/mottos_controller.rb
class MottosController < ApplicationController
  before_action :set_motto, only: [:show, :edit, :update, :destroy]

  # GET /mottos
  # GET /mottos.json
  def index
    @mottos = Motto.all
  end

  # GET /mottos/1
  # GET /mottos/1.json
  def show
  end

  # GET /mottos/new
  def new
    @motto = Motto.new
  end

  # GET /mottos/1/edit
  def edit
  end

  # POST /mottos
  # POST /mottos.json
  def create
    @motto = Motto.new(motto_params)

    respond_to do |format|
      if @motto.save
        format.html { redirect_to @motto, notice: 'Motto was successfully created.' }
        format.json { render action: 'show', status: :created, location: @motto }
      else
        format.html { render action: 'new' }
        format.json { render json: @motto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mottos/1
  # PATCH/PUT /mottos/1.json
  def update
    respond_to do |format|
      if @motto.update(motto_params)
        format.html { redirect_to @motto, notice: 'Motto was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @motto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mottos/1
  # DELETE /mottos/1.json
  def destroy
    @motto.destroy
    respond_to do |format|
      format.html { redirect_to mottos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_motto
      @motto = Motto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def motto_params
      params.require(:motto).permit(:motto, :mean, :surname_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/shields_controller.rb
class ShieldsController < ApplicationController
  before_action :set_shield, only: [:show, :edit, :update, :destroy]

  # GET /shields
  # GET /shields.json
  def index
    @shields = Shield.all
  end

  # GET /shields/1
  # GET /shields/1.json
  def show
  end

  # GET /shields/new
  def new
    @shield = Shield.new
  end

  # GET /shields/1/edit
  def edit
  end

  # POST /shields
  # POST /shields.json
  def create
    @shield = Shield.new(shield_params)

    respond_to do |format|
      if @shield.save
        format.html { redirect_to @shield, notice: 'Shield was successfully created.' }
        format.json { render action: 'show', status: :created, location: @shield }
      else
        format.html { render action: 'new' }
        format.json { render json: @shield.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shields/1
  # PATCH/PUT /shields/1.json
  def update
    respond_to do |format|
      if @shield.update(shield_params)
        format.html { redirect_to @shield, notice: 'Shield was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @shield.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shields/1
  # DELETE /shields/1.json
  def destroy
    @shield.destroy
    respond_to do |format|
      format.html { redirect_to shields_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shield
      @shield = Shield.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shield_params
      params.require(:shield).permit(:shield, :origin, :description, :surname_id)
    end
end

app/controllers/surnames_controller.rb
class SurnamesController < ApplicationController
  before_action :set_surname, only: [:show, :edit, :update, :destroy]

  # GET /surnames
  # GET /surnames.json
  def index
    @surnames = Surname.all
  end

  # GET /surnames/1
  # GET /surnames/1.json
  def show
  end

  # GET /surnames/new
  def new
    @surname = Surname.new
  end

  # GET /surnames/1/edit
  def edit
  end

  # POST /surnames
  # POST /surnames.json
  def create
    @surname = Surname.new(surname_params)

    respond_to do |format|
      if @surname.save
        format.html { redirect_to @surname, notice: 'Surname was successfully created.' }
        format.json { render action: 'show', status: :created, location: @surname }
      else
        format.html { render action: 'new' }
        format.json { render json: @surname.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surnames/1
  # PATCH/PUT /surnames/1.json
  def update
    respond_to do |format|
      if @surname.update(surname_params)
        format.html { redirect_to @surname, notice: 'Surname was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @surname.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surnames/1
  # DELETE /surnames/1.json
  def destroy
    @surname.destroy
    respond_to do |format|
      format.html { redirect_to surnames_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_surname
      @surname = Surname.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def surname_params
      params.require(:surname).permit(:surname, :history, :shield, :origin, :description)
    end
end

app/controllers/tartans_controller.rb
class TartansController < ApplicationController
  before_action :set_tartan, only: [:show, :edit, :update, :destroy]

  # GET /tartans
  # GET /tartans.json
  def index
    @tartans = Tartan.all
  end

  # GET /tartans/1
  # GET /tartans/1.json
  def show
  end

  # GET /tartans/new
  def new
    @tartan = Tartan.new
  end

  # GET /tartans/1/edit
  def edit
  end

  # POST /tartans
  # POST /tartans.json
  def create
    @tartan = Tartan.new(tartan_params)

    respond_to do |format|
      if @tartan.save
        format.html { redirect_to @tartan, notice: 'Tartan was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tartan }
      else
        format.html { render action: 'new' }
        format.json { render json: @tartan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tartans/1
  # PATCH/PUT /tartans/1.json
  def update
    respond_to do |format|
      if @tartan.update(tartan_params)
        format.html { redirect_to @tartan, notice: 'Tartan was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tartan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tartans/1
  # DELETE /tartans/1.json
  def destroy
    @tartan.destroy
    respond_to do |format|
      format.html { redirect_to tartans_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tartan
      @tartan = Tartan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tartan_params
      params.require(:tartan).permit(:tartan, :tartext, :surname_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mottos_helper.rb
module MottosHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/shields_helper.rb
module ShieldsHelper
end

app/helpers/surnames_helper.rb
module SurnamesHelper
end

app/helpers/tartans_helper.rb
module TartansHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- <div class="container-fluid"> -->
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag("logo.png"), root_path, :class=>'navbar-brand', :style => 'padding-top: 10px;' %>
      <!-- <a class="navbar-brand" href="#">Brand</a> -->
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blazquest</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>

<div class="container">
	<%= yield %>
</div>

</body>
</html>

app/views/mottos/_form.html.erb
<%= form_for(@motto) do |f| %>
  <% if @motto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@motto.errors.count, "error") %> prohibited this motto from being saved:</h2>

      <ul>
      <% @motto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :motto %><br>
    <%= f.text_field :motto %>
  </div>
  <div class="field">
    <%= f.label :mean %><br>
    <%= f.text_field :mean %>
  </div>
  <div class="field">
    <%= f.label :surname_id %><br>
    <%= f.number_field :surname_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mottos/edit.html.erb
<h1>Editing motto</h1>

<%= render 'form' %>

<%= link_to 'Show', @motto %> |
<%= link_to 'Back', mottos_path %>

app/views/mottos/index.html.erb
<h1>Listing mottos</h1>

<table>
  <thead>
    <tr>
      <th>Motto</th>
      <th>Mean</th>
      <th>Surname</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @mottos.each do |motto| %>
      <tr>
        <td><%= motto.motto %></td>
        <td><%= motto.mean %></td>
        <td><%= motto.surname_id %></td>
        <td><%= link_to 'Show', motto %></td>
        <td><%= link_to 'Edit', edit_motto_path(motto) %></td>
        <td><%= link_to 'Destroy', motto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Motto', new_motto_path %>

app/views/mottos/new.html.erb
<h1>New motto</h1>

<%= render 'form' %>

<%= link_to 'Back', mottos_path %>

app/views/mottos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Motto:</strong>
  <%= @motto.motto %>
</p>

<p>
  <strong>Mean:</strong>
  <%= @motto.mean %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @motto.surname_id %>
</p>

<%= link_to 'Edit', edit_motto_path(@motto) %> |
<%= link_to 'Back', mottos_path %>

app/views/pages/index.html.erb
<div class="jumbotron" align="center" style="background-image:url(/assets/bg.jpg)">
  	<div class="container">
  		<h2>Conoce el significado de tu apellido</h2>

    <form class="form-search form-inline">
        <div class="input-group">
            <input type="text" class="form-control search-query input-lg" placeholder="Search..." /> <span class="input-group-btn">
            <button type="submit" class="btn btn-primary btn-lg">Buscar</button>
            </span>

        </div>
    </form>


 	</div>
</div>

app/views/shields/_form.html.erb
<%= form_for(@shield) do |f| %>
  <% if @shield.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shield.errors.count, "error") %> prohibited this shield from being saved:</h2>

      <ul>
      <% @shield.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :shield %><br>
    <%= f.text_field :shield %>
  </div>
  <div class="field">
    <%= f.label :origin %><br>
    <%= f.text_field :origin %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :surname_id %><br>
    <%= f.number_field :surname_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shields/edit.html.erb
<h1>Editing shield</h1>

<%= render 'form' %>

<%= link_to 'Show', @shield %> |
<%= link_to 'Back', shields_path %>

app/views/shields/index.html.erb
<h1>Listing shields</h1>

<table>
  <thead>
    <tr>
      <th>Shield</th>
      <th>Origin</th>
      <th>Description</th>
      <th>Surname</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @shields.each do |shield| %>
      <tr>
        <td><%= shield.shield %></td>
        <td><%= shield.origin %></td>
        <td><%= shield.description %></td>
        <td><%= shield.surname_id %></td>
        <td><%= link_to 'Show', shield %></td>
        <td><%= link_to 'Edit', edit_shield_path(shield) %></td>
        <td><%= link_to 'Destroy', shield, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shield', new_shield_path %>

app/views/shields/new.html.erb
<h1>New shield</h1>

<%= render 'form' %>

<%= link_to 'Back', shields_path %>

app/views/shields/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Shield:</strong>
  <%= @shield.shield %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @shield.origin %>
</p>

<p>
  <strong>Description:</strong>
  <%= @shield.description %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @shield.surname_id %>
</p>

<%= link_to 'Edit', edit_shield_path(@shield) %> |
<%= link_to 'Back', shields_path %>

app/views/surnames/_form.html.erb
<%= form_for(@surname) do |f| %>
  <% if @surname.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@surname.errors.count, "error") %> prohibited this surname from being saved:</h2>

      <ul>
      <% @surname.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :surname %><br>
    <%= f.text_field :surname %>
  </div>
  <div class="field">
    <%= f.label :history %><br>
    <%= f.text_area :history %>
  </div>
  <div class="field">
    <%= f.label :shield %><br>
    <%= f.text_field :shield %>
  </div>
  <div class="field">
    <%= f.label :origin %><br>
    <%= f.text_field :origin %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/surnames/edit.html.erb
<h1>Editing surname</h1>

<%= render 'form' %>

<%= link_to 'Show', @surname %> |
<%= link_to 'Back', surnames_path %>

app/views/surnames/index.html.erb
<h1>Listing surnames</h1>

<table>
  <thead>
    <tr>
      <th>Surname</th>
      <th>History</th>
      <th>Shield</th>
      <th>Origin</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @surnames.each do |surname| %>
      <tr>
        <td><%= surname.surname %></td>
        <td><%= surname.history %></td>
        <td><%= surname.shield %></td>
        <td><%= surname.origin %></td>
        <td><%= surname.description %></td>
        <td><%= link_to 'Show', surname %></td>
        <td><%= link_to 'Edit', edit_surname_path(surname) %></td>
        <td><%= link_to 'Destroy', surname, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Surname', new_surname_path %>

app/views/surnames/new.html.erb
<h1>New surname</h1>

<%= render 'form' %>

<%= link_to 'Back', surnames_path %>

app/views/surnames/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Surname:</strong>
  <%= @surname.surname %>
</p>

<p>
  <strong>History:</strong>
  <%= @surname.history %>
</p>

<p>
  <strong>Shield:</strong>
  <%= @surname.shield %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @surname.origin %>
</p>

<p>
  <strong>Description:</strong>
  <%= @surname.description %>
</p>

<%= link_to 'Edit', edit_surname_path(@surname) %> |
<%= link_to 'Back', surnames_path %>

app/views/tartans/_form.html.erb
<%= form_for(@tartan) do |f| %>
  <% if @tartan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tartan.errors.count, "error") %> prohibited this tartan from being saved:</h2>

      <ul>
      <% @tartan.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tartan %><br>
    <%= f.text_field :tartan %>
  </div>
  <div class="field">
    <%= f.label :tartext %><br>
    <%= f.text_area :tartext %>
  </div>
  <div class="field">
    <%= f.label :surname_id %><br>
    <%= f.number_field :surname_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tartans/edit.html.erb
<h1>Editing tartan</h1>

<%= render 'form' %>

<%= link_to 'Show', @tartan %> |
<%= link_to 'Back', tartans_path %>

app/views/tartans/index.html.erb
<h1>Listing tartans</h1>

<table>
  <thead>
    <tr>
      <th>Tartan</th>
      <th>Tartext</th>
      <th>Surname</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tartans.each do |tartan| %>
      <tr>
        <td><%= tartan.tartan %></td>
        <td><%= tartan.tartext %></td>
        <td><%= tartan.surname_id %></td>
        <td><%= link_to 'Show', tartan %></td>
        <td><%= link_to 'Edit', edit_tartan_path(tartan) %></td>
        <td><%= link_to 'Destroy', tartan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tartan', new_tartan_path %>

app/views/tartans/new.html.erb
<h1>New tartan</h1>

<%= render 'form' %>

<%= link_to 'Back', tartans_path %>

app/views/tartans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tartan:</strong>
  <%= @tartan.tartan %>
</p>

<p>
  <strong>Tartext:</strong>
  <%= @tartan.tartext %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @tartan.surname_id %>
</p>

<%= link_to 'Edit', edit_tartan_path(@tartan) %> |
<%= link_to 'Back', tartans_path %>